INSERT INTO CITIES (name) VALUES('ADANA'),
                                ('ADIYAMAN'),
                                ('AFYONKARAHİSAR'),
                                ('AĞRI'),
                                ('AMASYA'),
                                ('ANKARA'),
                                ('ANTALYA'),
                                ('ARTVİN'),
                                ('AYDIN'),
                                ('BALIKESİR'),
                                ('BİLECİK'),
                                ('BİNGÖL'),
                                ('BİTLİS'),
                                ('BOLU'),
                                ('BURDUR'),
                                ('BURSA'),
                                ('ÇANAKKALE'),
                                ('ÇANKIRI'),
                                ('ÇORUM'),
                                ('DENİZLİ'),
                                ('DİYARBAKIR'),
                                ('EDİRNE'),
                                ('ELAZIĞ'),
                                ('ERZİNCAN'),
                                ('ERZURUM'),
                                ('ESKİŞEHİR'),
                                ('GAZİANTEP'),
                                ('GİRESUN'),
                                ('GÜMÜŞHANE'),
                                ('HAKKARİ'),
                                ('HATAY'),
                                ('ISPARTA'),
                                ('MERSİN'),
                                ('İSTANBUL'),
                                ('İZMİR'),
                                ('KARS'),
                                ('KASTAMONU'),
                                ('KAYSERİ'),
                                ('KIRKLARELİ'),
                                ('KIRŞEHİR'),
                                ('KOCAELİ'),
                                ('KONYA'),
                                ('KÜTAHYA'),
                                ('MALATYA'),
                                ('MANİSA'),
                                ('KAHRAMANMARAŞ'),
                                ('MARDİN'),
                                ('MUĞLA'),
                                ('MUŞ'),
                                ('NEVŞEHİR'),
                                ('NİĞDE'),
                                ('ORDU'),
                                ('RİZE'),
                                ('SAKARYA'),
                                ('SAMSUN'),
                                ('SİİRT'),
                                ('SİNOP'),
                                ('SİVAS'),
                                ('TEKİRDAĞ'),
                                ('TOKAT'),
                                ('TRABZON'),
                                ('TUNCELİ'),
                                ('ŞANLIURFA'),
                                ('UŞAK'),
                                ('VAN'),
                                ('YOZGAT'),
                                ('ZONGULDAK'),
                                ('AKSARAY'),
                                ('BAYBURT'),
                                ('KARAMAN'),
                                ('KIRIKKALE'),
                                ('BATMAN'),
                                ('ŞIRNAK'),
                                ('BARTIN'),
                                ('ARDAHAN'),
                                ('IĞDIR'),
                                ('YALOVA'),
                                ('KARABÜK'),
                                ('KİLİS'),
                                ('OSMANİYE'),
                                ('DÜZCE');
insert into candidate_education_grade (id, grade)
values (1, 'Hazırlık'),
       (2, '1'),
       (3, '2'),
       (4, '3'),
       (5, '4'),
       (6, '5'),
       (7, 'Mezun');

insert into candidate_education_degree (id, degree)
values (1, 'Lise'),(2, 'Ön Lisans'),(3, 'Lisans'),(4, 'Doktora'),(5, 'Yüksek Lisans');